### ISSUE TITLE
alternative aproach

### ISSUE THREAD

**Issue by robert-aleksic** [apankrat/notes#1]
Hi, nice writeup and great idea.

I have done it quite differently. Lower and upper characters are relatively rare, they are seperated by either 32, 80 or 1 positions. Done it many times and it converged to following code for lowercase. (it is in pascal, but should be easily understood). It is just few comparations and few additions, 1 and 32 can be implemented by set/reset bits for example. It could be easily optimised further, but I found no need while processing 50GB's of csv. As of memory requirements, inner case statement is implemented by jump tables of size 256, so it's probably up to 5KB, last one can be implemented by comparison as well as others depending of expected frequency of leters so memory is certainly no issue here... It covers utf-8 for two byte codes, but can be easily extended for more if needed.

           #$41..#$5a : buff[le] := chr (ord(ch)+32); // 'A'..'Z'
           #$c0..#$df : begin // two byte unicode
                          b1 := ord(ch);
                          b2 := ord(buff[le+1]);
                          if (b2 and $c0) = $80 // proper second byte
                          then begin
                                 c1 := (b1 shr 2) and 7;
                                 c2 := (b2 and 63) or ((b1 mod 4) shl 6);

                                 case c1 of
                                   00 : case c2 of // latin supplement
                                          $c0..$de : if c2<>$d7 then c2 := c2+32;
                                          else
                                        end;
                                   01 : case c2 of // latin extended
                                          $00..$7d  : if ((c2 < $78) and not odd(c2)) or ((c2 > $78) and odd(c2)) then c2 := c2+1;
                                          $cd..$de  : if not odd(c2) then c2 := c2+1;
                                          else
                                        end;
                                   03 : case c2 of // greek
                                          $91..$ab  : c2 := c2+32;
                                          else
                                        end;
                                   04 : case c2 of // cyrilic
                                          $00..$0f  : c2 := c2+80;
                                          $10..$2f  : c2 := c2+32;
                                          $60..$81,
                                          $8a..$ff  : if not odd(c2) then c2 := c2+1;
                                          else
                                        end;
                                   05 : case c2 of // cyrilic suplement
                                          $00..$2f  : if not odd(c2) then c2 := c2+1;
                                          else
                                        end;
                                   else

                                 b1 := ((c1 and 7) shl 2) or (c2 shr 6) or $c0;
                                 b2 := (c2 and 63) or $80
                               end;
                          buff[le]   := chr(b1);
                          buff[le+1] := chr(b2);
                          le := le+1
                        end

**Comment by apankrat** [comment]
Robert, your code handles Unicode symbols up to 0x07FF max. Once you look beyond that the upper/lowercase deltas will have values other than 1, 32 and 80. Have a look [here](/fast-case-conversion/tolower-table.txt).

Edit - There are 74 different delta values.

**Comment by robert-aleksic** [comment]
HI, thanks for the info and apologies, I, never had a need to go out of that range.
